baseURL = 'https://www.peroniko.xyz/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = "Nikola Perović"
theme = ["hugo-cloak-email", "m10c"]
paginate = 8
canonifyURLs = true

[languages]
  [languages.en]
    title = "Nikola Perović"
    languageName = "English"
    weight = 1
  [languages.sr]
    title = "Nikola Perović"
    languageName = "SR-MN"
    weight = 2

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
[[menu.main.sr]]
name = "Početna"
url = "/sr/"
weight = 1
[[menu.main.sr]]
name = "Tags"
url = "/sr/tags/"
weight = 2
[[menu.main.sr]]
name = "O sajtu"
url = "/sr/about/"
weight = 3

[params]
favicon = "/favicon.svg"
avatar = "/avatar.webp"
menu_item_separator = "·"
stylesheet = "/style.css"
indexarticles = 10
taglist = true
googleAnalyticsID = "G-7XL7CEV7EW"
# Author
author = "Nikola Perović"
# Description
description = "This is my website where I talk about stuff I'm into. Right now, I'm studying philosophy, but I'm also really interested in Linux and FOSS, film and its history, literature and music."
image = "/avatar.webp"
images = ["/featured.svg"]
# Social links
[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/Fooftilly"
[[params.social]]
icon = "youtube"
name = "Youtube"
url = "https://www.youtube.com/channel/UC94TNPxReYOsZculkHjyS0Q"
[[params.social]]
icon = "letterboxd"
name = "Letterboxd"
url = "https://letterboxd.com/Fooftilly"
[[params.social]]
icon = "trakt"
name = "Trakt"
url = "https://trakt.tv/users/cobe10"
[[params.social]]
icon = "music"
name = "RateYourMusic"
url = "https://rateyourmusic.com/~Fooftilly"
[[params.social]]
icon = "rss"
name = "RSS"
url = "https://www.peroniko.xyz/index.xml"
# Default theme
[params.style]
darkestColor = "#242930"
darkColor = "#353b43"
lightColor = "#fae3bb"
lightestColor = "#f3cc2c"
primaryColor = "#d1cae7"

[params.giscus]
repo = "Fooftilly/Fooftilly.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkyMTk4Mjg5MTg="
category = "Articles"
categoryID = "DIC_kwDODRpSts4CUNb-"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "dark_dimmed"
lang = "en"
loading = "lazy"

[social]
twitter = 'GregoryKentch'

[sitemap]
changefreq = 'always'
filename = 'sitemap.xml'
priority = 0.5
